export const STATUS_TONES: Record<string, string> = {
  // artifact-factory LaneStage (adws/adw_modules/scheduler_types.py::LaneStage)
  planned: "pending",
  writing_tests: "info",
  reviewing_tests: "review",
  tests_sealed: "ok",
  building: "info",
  reviewing_code: "review",
  ready_to_merge: "ready",
  waiting_for_user: "warn",
  merged: "ok",
  verified: "ok",
  accepted: "ok",
  ok: "ok",
  running: "info",
  cancelling: "warn",
  reviewing: "review",
  candidate_ready: "review",
  waiting_for_new_candidate: "review",
  repair_handoff: "warn",
  repairing: "warn",
  pending: "pending",
  quiescent: "pending",
  empty: "pending",
  ready: "ready",
  blocked: "warn",
  warning: "warn",
  cancelled: "err",
  stuck: "err",
  failed: "err",
  stale: "warn",
  abandoned: "warn",
  unknown: "pending",
  not_recorded: "pending",
  not_running: "pending",
};
